# Generated by Django 4.0.3 on 2022-04-18 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='takenbooks',
            old_name='fine',
            new_name='fines',
        ),
        migrations.RenameField(
            model_name='takenbooks',
            old_name='renewaldate',
            new_name='renewaldat',
        ),
        migrations.RenameField(
            model_name='takenbooks',
            old_name='renewalstatus',
            new_name='renewalstat',
        ),
        migrations.RenameField(
            model_name='takenbooks',
            old_name='returndaate',
            new_name='returndate',
        ),
        migrations.RenameField(
            model_name='takenbooks',
            old_name='returnstatus',
            new_name='returnstat',
        ),
    ]
