# Generated by Django 4.0.3 on 2022-04-18 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_fine_takenbooks_fines_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takenbooks',
            name='fines',
        ),
        migrations.RemoveField(
            model_name='takenbooks',
            name='renewaldat',
        ),
        migrations.RemoveField(
            model_name='takenbooks',
            name='renewalstat',
        ),
        migrations.RemoveField(
            model_name='takenbooks',
            name='returndate',
        ),
        migrations.RemoveField(
            model_name='takenbooks',
            name='returnstat',
        ),
    ]
