# Generated by Django 4.0.3 on 2022-04-18 18:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_takenbooks_fines_remove_takenbooks_renewaldat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='takenbooks',
            name='fines',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='takenbooks',
            name='renewaldat',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='takenbooks',
            name='renewalstat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='takenbooks',
            name='returndate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='takenbooks',
            name='returnstat',
            field=models.BooleanField(default=False),
        ),
    ]
