# Generated by Django 4.0.3 on 2022-04-18 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_fines_takenbooks_fine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takenbooks',
            name='fine',
        ),
    ]
