# Generated by Django 4.0.3 on 2022-04-18 19:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_booktakingdatabase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktakingdatabase',
            name='returndate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='booktakingdatabase',
            name='takendate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
