# Generated by Django 4.0.3 on 2022-04-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesadmin',
            name='quesadmin_username',
            field=models.CharField(max_length=30),
        ),
    ]
