# Generated by Django 4.0.3 on 2022-04-19 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0002_alter_quesadmin_quesadmin_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesadmin',
            name='quesadmin_username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
